import Command

TMFM_WP = 1
TMFM_AV = 2
TMFM_AU = 3

MD_AV_START_SCAN = 1
TMCMD_AV_STOP_SCAN = 2
TMCMD_AV_PAUSE_SCAN = 3
TMCMD_AV_RESUME_SCAN = 4
TMCMD_AV_START_SCHED_SCAN = 5
TMCMD_AV_CANCEL_SCHED_SCAN = 6
TMCMD_AV_DELAY_SCHED_SCAN = 7
TMCMD_AV_ENABLE_RTSCAN = 8
TMCMD_AV_DISABLE_RTSCAN = 9
TMCMD_AV_ENABLE_SCHED_SCAN = 10
TMCMD_AV_DISABLE_SCHED_SCAN = 11

if __name__=="__main__":

    nRet=Command.Test_TmccSendCommand( TMFM_AV, TMCMD_AV_STOP_SCAN )
    print nRet
 
